#include <Adafruit_BME280.h>
#include <Adafruit_GFX.h>
#include <Adafruit_NeoPixel.h>
#include <Adafruit_SSD1306.h>
#include <colors.h>
#include <Ethernet.h>
#include <Encoder.h>
#include <hue.h>
#include <mac.h>
#include <OneButton.h>
#include <SD.h>
#include <SPI.h>
#include <wemo.h> 
#include <Wire.h>
